### ISSUE TITLE
ProtGNN+ usage

### ISSUE THREAD

**Issue by gserpep** [zaixizhang/ProtGNN#4]
Hello,
I would like to reproduce the results of the paper related to ProtGNN+. In particular, I am interested in reproducing the results of the reasoning process, similarly to what is reported in Figure 3 of the work. However, in the current version of the repo, I think I am missing how to do it. Could you please provide code/instructions to run ProtGNN+ and visualize the corresponding reasoning process? 

Thanks!

**Comment by zaixizhang** [comment]
Thanks for your interest in our work! In the github repo, we mainly provide the code to run ProtGNN. The ProtGNN+ model can be obtained with minor modifications. For example, the subgraphs in Figure.3 can be obtained with the trained edge_mask function. You can train edge_mask along with ProtGNN model following the instructions in the paper.
